import dynamic from "next/dynamic";

const Inter = dynamic(() => import("next/font/google"), {
  ssr: false, // Ensure the font is not imported during server-side rendering
});

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "rgb(48, 118, 114)" }}>
        <style>{`
          ${inter.styles}
          /* Additional CSS styles can be added here */
        `}</style>
        {children}
      </body>
    </html>
  );
}
